[package]
name = "show-recent-activity-for-github-bot"
version = "0.1.0"
authors = ["Michael Howell <michael@notriddle.com>"]

[dependencies]
clap = "2.24"
hyper = "0.10"
hyper-native-tls = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
